"""empty message

Revision ID: 01747998cc27
Revises: 35b50c3f3076
Create Date: 2022-02-06 01:30:47.017401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01747998cc27'
down_revision = '35b50c3f3076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
