"""empty message

Revision ID: 0489fa2799af
Revises: 4108650510dd
Create Date: 2022-02-06 01:17:53.009147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0489fa2799af'
down_revision = '4108650510dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
