"""empty message

Revision ID: 0566ee4f927a
Revises: 85ae07287839
Create Date: 2022-01-12 17:53:09.529412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0566ee4f927a'
down_revision = '85ae07287839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
