"""empty message

Revision ID: 0b01ee2339e8
Revises: 3a9217e7bf1a
Create Date: 2022-01-17 22:46:56.656927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b01ee2339e8'
down_revision = '3a9217e7bf1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
