"""empty message

Revision ID: 0b72d5761dc0
Revises: 61cca79bcd84
Create Date: 2022-01-22 21:56:32.838775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b72d5761dc0'
down_revision = '61cca79bcd84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
