"""empty message

Revision ID: 0dc62fe0c80d
Revises: d0bd6625045f
Create Date: 2022-02-05 00:43:07.296657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc62fe0c80d'
down_revision = 'd0bd6625045f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
