"""empty message

Revision ID: 181f5a918fca
Revises: 8f22e56fd6f5
Create Date: 2022-01-16 12:02:21.963207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181f5a918fca'
down_revision = '8f22e56fd6f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
