"""empty message

Revision ID: 1930a909c2bc
Revises: 0566ee4f927a
Create Date: 2022-01-12 17:58:12.103666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1930a909c2bc'
down_revision = '0566ee4f927a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
