"""empty message

Revision ID: 19c3706cf62c
Revises: 27adf5bda0dc
Create Date: 2021-12-31 19:29:00.395213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c3706cf62c'
down_revision = '27adf5bda0dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
