"""empty message

Revision ID: 1d63944ee0a1
Revises: 78e72d912b1d
Create Date: 2022-01-12 21:35:50.818072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d63944ee0a1'
down_revision = '78e72d912b1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
