"""empty message

Revision ID: 20a1f18438cc
Revises: 1d63944ee0a1
Create Date: 2022-01-12 21:38:47.200391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a1f18438cc'
down_revision = '1d63944ee0a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
