"""empty message

Revision ID: 269d38856ddb
Revises: da296090900f
Create Date: 2022-01-22 22:08:12.167962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269d38856ddb'
down_revision = 'da296090900f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
