"""empty message

Revision ID: 27adf5bda0dc
Revises: 9d6fc996da1c
Create Date: 2021-12-31 17:52:42.473949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27adf5bda0dc'
down_revision = '9d6fc996da1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
