"""empty message

Revision ID: 2b0d93afb93e
Revises: 411140069c48
Create Date: 2022-01-23 22:34:47.314703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0d93afb93e'
down_revision = '411140069c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
