"""empty message

Revision ID: 2e4638f27210
Revises: 63d3e837e58e
Create Date: 2022-01-11 23:07:23.691348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4638f27210'
down_revision = '63d3e837e58e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
