"""empty message

Revision ID: 2f5389021219
Revises: 82b8e561df87
Create Date: 2022-01-22 14:41:36.789161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5389021219'
down_revision = '82b8e561df87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
