"""empty message

Revision ID: 32e4108070db
Revises: 8797b67ec7da
Create Date: 2022-02-06 15:45:41.331770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32e4108070db'
down_revision = '8797b67ec7da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
