"""empty message

Revision ID: 355ada31e510
Revises: 9eefae4fe2d8
Create Date: 2022-01-11 16:46:30.203512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355ada31e510'
down_revision = '9eefae4fe2d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
