"""empty message

Revision ID: 35b50c3f3076
Revises: 0489fa2799af
Create Date: 2022-02-06 01:25:37.660126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b50c3f3076'
down_revision = '0489fa2799af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
