"""empty message

Revision ID: 365b20ce1f2b
Revises: 8aa6a067c204
Create Date: 2022-01-16 12:24:10.881705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365b20ce1f2b'
down_revision = '8aa6a067c204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
