"""empty message

Revision ID: 3754fd0e7a11
Revises: 01747998cc27
Create Date: 2022-02-06 14:57:28.802581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3754fd0e7a11'
down_revision = '01747998cc27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
