"""empty message

Revision ID: 3a438eb8a0d4
Revises: 7b3468ea717c
Create Date: 2022-01-16 11:55:46.528564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a438eb8a0d4'
down_revision = '7b3468ea717c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
