"""empty message

Revision ID: 3a9217e7bf1a
Revises: bc91f057a0b2
Create Date: 2022-01-16 23:43:07.218888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9217e7bf1a'
down_revision = 'bc91f057a0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
