"""empty message

Revision ID: 3bd33ec1f366
Revises: 20a1f18438cc
Create Date: 2022-01-15 22:30:45.401942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bd33ec1f366'
down_revision = '20a1f18438cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
