"""empty message

Revision ID: 3cc7b59a357c
Revises: c4395deabbb1
Create Date: 2022-01-17 23:24:41.841567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc7b59a357c'
down_revision = 'c4395deabbb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
