"""empty message

Revision ID: 4108650510dd
Revises: 0dc62fe0c80d
Create Date: 2022-02-05 00:45:23.738014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4108650510dd'
down_revision = '0dc62fe0c80d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
