"""empty message

Revision ID: 411140069c48
Revises: 775876ee2e9b
Create Date: 2022-01-23 19:24:18.638384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411140069c48'
down_revision = '775876ee2e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
