"""empty message

Revision ID: 52f157ce6c8e
Revises: 
Create Date: 2021-12-31 17:12:51.484285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f157ce6c8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('prefix', sa.String(length=8), server_default='g!', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guild')
    # ### end Alembic commands ###
