"""empty message

Revision ID: 5b76ccc8202f
Revises: 1930a909c2bc
Create Date: 2022-01-12 18:10:51.514249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b76ccc8202f'
down_revision = '1930a909c2bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
