"""empty message

Revision ID: 61cca79bcd84
Revises: 881672796d4f
Create Date: 2022-01-22 21:49:38.717349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61cca79bcd84'
down_revision = '881672796d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
