"""empty message

Revision ID: 63a10615c492
Revises: 3cc7b59a357c
Create Date: 2022-01-18 21:09:27.295040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a10615c492'
down_revision = '3cc7b59a357c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
