"""empty message

Revision ID: 63d3e837e58e
Revises: 6db8ccc0a79d
Create Date: 2022-01-11 22:30:41.183996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d3e837e58e'
down_revision = '6db8ccc0a79d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
