"""empty message

Revision ID: 677e568216aa
Revises: a6e559f0b673
Create Date: 2022-01-22 12:30:37.265297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677e568216aa'
down_revision = 'a6e559f0b673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
