"""empty message

Revision ID: 6922aaad0e83
Revises: 99d87000c153
Create Date: 2022-01-16 00:08:41.490952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6922aaad0e83'
down_revision = '99d87000c153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
