"""empty message

Revision ID: 6d07f4146cc3
Revises: 941abe6b4572
Create Date: 2022-01-11 16:23:40.774050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d07f4146cc3'
down_revision = '941abe6b4572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
