"""empty message

Revision ID: 6db8ccc0a79d
Revises: dce32799c362
Create Date: 2022-01-11 22:22:56.671354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db8ccc0a79d'
down_revision = 'dce32799c362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
