"""empty message

Revision ID: 7009004e00b4
Revises: ddf2fc054346
Create Date: 2021-12-31 17:15:45.907393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7009004e00b4'
down_revision = 'ddf2fc054346'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
