"""empty message

Revision ID: 74ac3b7b51e8
Revises: cde0e5c61196
Create Date: 2022-01-11 16:58:29.483907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ac3b7b51e8'
down_revision = 'cde0e5c61196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
