"""empty message

Revision ID: 775876ee2e9b
Revises: c2d1a92ee077
Create Date: 2022-01-23 18:35:41.915737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775876ee2e9b'
down_revision = 'c2d1a92ee077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
