"""empty message

Revision ID: 78e72d912b1d
Revises: 5b76ccc8202f
Create Date: 2022-01-12 21:23:48.731676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e72d912b1d'
down_revision = '5b76ccc8202f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
