"""empty message

Revision ID: 7b3468ea717c
Revises: 6922aaad0e83
Create Date: 2022-01-16 00:10:18.423589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3468ea717c'
down_revision = '6922aaad0e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
