"""empty message

Revision ID: 81f6e0cd882d
Revises: d80da067617e
Create Date: 2022-01-17 23:03:33.471896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f6e0cd882d'
down_revision = 'd80da067617e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
