"""empty message

Revision ID: 82b8e561df87
Revises: bece9ef2e4e4
Create Date: 2022-01-22 14:08:18.849609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82b8e561df87'
down_revision = 'bece9ef2e4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
