"""empty message

Revision ID: 85ae07287839
Revises: dbea889a4d5e
Create Date: 2022-01-12 16:41:31.758591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ae07287839'
down_revision = 'dbea889a4d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
