"""empty message

Revision ID: 8797b67ec7da
Revises: 3754fd0e7a11
Create Date: 2022-02-06 15:00:41.316772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8797b67ec7da'
down_revision = '3754fd0e7a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
