"""empty message

Revision ID: 87cd2b257d08
Revises: d5105f2dc0e2
Create Date: 2022-01-16 23:22:40.234187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87cd2b257d08'
down_revision = 'd5105f2dc0e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
