"""empty message

Revision ID: 881672796d4f
Revises: eb291d1240f7
Create Date: 2022-01-22 21:20:02.499024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881672796d4f'
down_revision = 'eb291d1240f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
