"""empty message

Revision ID: 8aa6a067c204
Revises: 181f5a918fca
Create Date: 2022-01-16 12:11:37.630228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa6a067c204'
down_revision = '181f5a918fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
