"""empty message

Revision ID: 8f22e56fd6f5
Revises: 3a438eb8a0d4
Create Date: 2022-01-16 11:58:36.507492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f22e56fd6f5'
down_revision = '3a438eb8a0d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
