"""empty message

Revision ID: 91183478c16e
Revises: 9193405a2303
Create Date: 2022-01-11 22:17:26.460506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91183478c16e'
down_revision = '9193405a2303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
