"""empty message

Revision ID: 9193405a2303
Revises: 9d34855c56f2
Create Date: 2022-01-11 21:43:25.945971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9193405a2303'
down_revision = '9d34855c56f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
