"""empty message

Revision ID: 941abe6b4572
Revises: 19c3706cf62c
Create Date: 2022-01-11 16:07:23.836763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941abe6b4572'
down_revision = '19c3706cf62c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
