"""empty message

Revision ID: 9d34855c56f2
Revises: 74ac3b7b51e8
Create Date: 2022-01-11 17:02:02.153193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d34855c56f2'
down_revision = '74ac3b7b51e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
