"""empty message

Revision ID: 9d6fc996da1c
Revises: 7009004e00b4
Create Date: 2021-12-31 17:49:58.679441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6fc996da1c'
down_revision = '7009004e00b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
