"""empty message

Revision ID: 9eefae4fe2d8
Revises: 6d07f4146cc3
Create Date: 2022-01-11 16:44:49.414369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eefae4fe2d8'
down_revision = '6d07f4146cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
