"""empty message

Revision ID: a6e559f0b673
Revises: 63a10615c492
Create Date: 2022-01-20 22:29:43.488413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e559f0b673'
down_revision = '63a10615c492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
