"""empty message

Revision ID: bece9ef2e4e4
Revises: 677e568216aa
Create Date: 2022-01-22 12:35:01.144365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bece9ef2e4e4'
down_revision = '677e568216aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
