"""empty message

Revision ID: c2d1a92ee077
Revises: fa9eccb79a66
Create Date: 2022-01-22 22:37:32.920029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d1a92ee077'
down_revision = 'fa9eccb79a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
