"""empty message

Revision ID: c4395deabbb1
Revises: 81f6e0cd882d
Create Date: 2022-01-17 23:20:59.417836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4395deabbb1'
down_revision = '81f6e0cd882d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
