"""empty message

Revision ID: cde0e5c61196
Revises: 355ada31e510
Create Date: 2022-01-11 16:54:14.521449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cde0e5c61196'
down_revision = '355ada31e510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
