"""empty message

Revision ID: d0bd6625045f
Revises: 2b0d93afb93e
Create Date: 2022-02-04 23:41:17.153427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0bd6625045f'
down_revision = '2b0d93afb93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
