"""empty message

Revision ID: d5105f2dc0e2
Revises: 365b20ce1f2b
Create Date: 2022-01-16 23:19:58.590243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5105f2dc0e2'
down_revision = '365b20ce1f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
