"""empty message

Revision ID: d80da067617e
Revises: 0b01ee2339e8
Create Date: 2022-01-17 22:49:23.582259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd80da067617e'
down_revision = '0b01ee2339e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
