"""empty message

Revision ID: da296090900f
Revises: 0b72d5761dc0
Create Date: 2022-01-22 22:04:30.959003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da296090900f'
down_revision = '0b72d5761dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
