"""empty message

Revision ID: dbea889a4d5e
Revises: ca4f77fb50fd
Create Date: 2022-01-12 16:35:28.722503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbea889a4d5e'
down_revision = 'ca4f77fb50fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
