"""empty message

Revision ID: ddf2fc054346
Revises: ed831df4fc4a
Create Date: 2021-12-31 17:14:28.290378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf2fc054346'
down_revision = 'ed831df4fc4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
