"""empty message

Revision ID: e007b420438d
Revises: eb2b0cf7861f
Create Date: 2022-02-06 17:41:07.972409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e007b420438d'
down_revision = 'eb2b0cf7861f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
