"""empty message

Revision ID: eb291d1240f7
Revises: 2f5389021219
Create Date: 2022-01-22 16:19:52.010148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb291d1240f7'
down_revision = '2f5389021219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
