"""empty message

Revision ID: eb2b0cf7861f
Revises: 32e4108070db
Create Date: 2022-02-06 15:50:39.312627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2b0cf7861f'
down_revision = '32e4108070db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
