"""empty message

Revision ID: ed831df4fc4a
Revises: 52f157ce6c8e
Create Date: 2021-12-31 17:13:50.364823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed831df4fc4a'
down_revision = '52f157ce6c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
