"""empty message

Revision ID: f1fc2d876a24
Revises: 3bd33ec1f366
Create Date: 2022-01-15 23:03:06.748302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fc2d876a24'
down_revision = '3bd33ec1f366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
