"""empty message

Revision ID: fa9eccb79a66
Revises: 86e598332920
Create Date: 2022-01-22 22:33:27.661776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9eccb79a66'
down_revision = '86e598332920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
